# --- Default Configuration of System ---
CONFIG_LOG=y
CONFIG_LOG_MODE_DEFERRED=y

# --- Shell's Configuration (CLI) ---
CONFIG_SHELL=y
CONFIG_SHELL_PROMPT_UART="smid:~$ "

# --- Optimization of ESP32-S3 ---
CONFIG_FPU=y  # Float Point Unit
